# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
page:
  apiPath: ${API_PATH:${java.io.tmpdir}/api}
  dbPath: ${DB_PATH:${java.io.tmpdir}/db}
  dbName: ${DB_NAME:pagedb}
  exchangeratesapi.io:
    base-currency: EUR # AUD,USD - base_currency_access_restricted
    base-url: https://api.exchangeratesapi.io/v1
    access-key: ${EXCHANGERATESAPI_ACCESS_KEY:accessKey}
    cron: '@daily'
  marketstack.com:
    default-currency: USD
    base-url: https://api.marketstack.com/v2
    access-key: ${MARKETSTACK_ACCESS_KEY:accessKey}
    cron: 0 0 8 * * *
  test:
    cron: '@daily'

logging:
  level:
    com.totemsoft.page: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG
    org.apache.tomcat.util.http: ERROR
    org.apache.catalina.connector.CoyoteAdapter: ERROR
    org.apache.coyote.http11.Http11Processor: ERROR

management:
  endpoints:
    access:
      default: false

spring:
  application:
    name: Page Builder
  datasource:
    url: jdbc:h2:file:${page.dbPath}/${page.dbName};MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 0
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: none # disable automatic DDL generation to avoid conflicts
    open-in-view: false
    show-sql: false
    properties:
    - hibernate.connection.provider_disables_autocommit: true
  main:
    lazy-initialization: true
  messages:
    basename: messages
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
            - openid
            - profile
            - email
  # TODO: move to H2 specific profile
  sql:
    init:
      #continue-on-error: true # continue when duplicate data load error occurs (data.sql)
      mode: always
      schema-locations: optional:classpath*:schema.sql
      data-locations: optional:classpath*:data.sql
  transaction:
    rollback-on-commit-failure: true
  web:
    resources:
      cache:
        period: 15
        cachecontrol:
          cache-private: true
          max-age: 1d
          must-revalidate: true
          no-cache: true

# --------------------------------------------------------- #
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
# --------------------------------------------------------- #
server:
  port: 8080
  servlet:
    context-path: /
    application-display-name: Page Builder
  tomcat:
    accesslog:
      max-days: 1
      request-attributes-enabled: true
