# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

logging:
  level:
    com.totemsoft.page: DEBUG

spring:
  application:
    name: Page Builder
  devtools.add-properties: false
  jackson:
    default-property-inclusion: non_null
  jpa:
    # disable automatic DDL generation to avoid conflicts
    hibernate.ddl-auto: none
    open-in-view: false
  messages:
    basename: messages
  # For non-embedded databases explicitly enable initialization (schema.sql, data.sql)
  #sql.init.mode: always
# Set the Cache-Control max-age for static resources to 1 day
  resources:
    cache-period: 15
    cache:
      cachecontrol:
        max-age: 1d
        no-cache: true
  thymeleaf:
    #cache: false # Disable Thymeleaf cache (useful for development)
    cache: true  # Enable Thymeleaf cache (default for production)
    cache-ttl: 3600000

# --------------------------------------------------------- #
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
# --------------------------------------------------------- #
server:
  port: 8080
  servlet:
    context-path: /
    application-display-name: Page Builder
