# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html

logging:
  level:
    com.totemsoft.page: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG

management:
  endpoints:
    access:
      default: false

spring:
  application:
    name: Page Builder
  datasource:
    url: jdbc:h2:file:${java.io.tmpdir}/db/pagedb # /tmp/pagedb.mv.db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  devtools:
    add-properties: false
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: none # disable automatic DDL generation to avoid conflicts
    open-in-view: false
#    properties:
#    - hibernate.bytecode.provider: none
#    - hibernate.enhancer.enableDirtyTracking: false
#    - hibernate.enhancer.enableLazyInitialization: false
  main:
    lazy-initialization: true
  messages:
    basename: messages
  # TODO: move to H2 specific profile
  sql:
    init:
      continue-on-error: true
      mode: always
      #schema-locations: classpath:/db/migration/*.sql
      #data-locations: classpath:/db/migration/data/*.sql
  web:
    resources:
      cache:
        period: 15
        cachecontrol:
          cache-private: true
          max-age: 1d
          must-revalidate: true
          no-cache: true

# --------------------------------------------------------- #
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
# --------------------------------------------------------- #
server:
  port: 8080
  servlet:
    context-path: /
    application-display-name: Page Builder
  tomcat:
    accesslog:
      max-days: 1
      request-attributes-enabled: true
