create schema if not exists public;

use public;

create table if not exists currency (
  currency_code char(3) not null,
  currency_title varchar(255) not null,
  currency_base char(1),
  primary key (currency_code)
);

create table if not exists exchange_rate (
  currency_date date not null,
  currency_base char(3) not null,
  currency_code char(3) not null,
  currency_rate numeric(38,2) not null,
  currency_timestamp timestamp not null,
  constraint exchange_rate_fk1 foreign key (currency_code) references currency (currency_code),
  constraint exchange_rate_fk2 foreign key (currency_base) references currency (currency_code),
  primary key (currency_date, currency_base, currency_code)
);

create table if not exists exchange (
  exchange_mic varchar(5) not null,
  exchange_name varchar(255) not null,
  exchange_acronym varchar(255),
  exchange_country varchar(255),
  exchange_country_code varchar(255),
  exchange_city varchar(255),
  exchange_website varchar(255),
  exchange_operating_mic varchar(255),
  exchange_oprt_sgmt varchar(255),
  exchange_legal_entity_name varchar(255),
  exchange_exchange_lei varchar(255),
  exchange_market_category_code varchar(255),
  exchange_exchange_status varchar(255),
  exchange_date_creation date,
  exchange_date_last_update date,
  exchange_date_last_validation date,
  exchange_date_expiry date,
  exchange_comments varchar(255),
  exchange_base char(1),
  primary key (exchange_mic)
);

create table if not exists exchange_ticker (
  exchange_mic varchar(5) not null,
  ticker_symbol varchar(32) not null,
  ticker_name varchar(255),
  ticker_has_intraday char(1),
  ticker_has_eod char(1),
  ticker_base char(1),
  primary key (exchange_mic, ticker_symbol)
);

create table if not exists split_ratio (
  split_ratio_name varchar(32) not null,
  split_ratio_title varchar(255) not null,
  primary key (split_ratio_name)
);

create table if not exists tag_type (
  tag_type_id int generated by default as identity,
  tag_type_name varchar(32) not null,
  tag_type_title varchar(255),
  primary key (tag_type_id)
);
create unique index if not exists tag_type_uk1 on tag_type (tag_type_name);

create table if not exists tag (
  tag_id bigint generated by default as identity,
  tag_name varchar(32) not null,
  tag_title varchar(255),
  tag_type_id int not null,
  constraint tag_fk1 foreign key (tag_type_id) references tag_type (tag_type_id),
  primary key (tag_id)
);
create unique index if not exists tag_idx1 on tag (tag_type_id, tag_name);

create table if not exists page (
  page_id bigint generated by default as identity,
  page_name varchar(255) not null,
  primary key (page_id)
);
create unique index if not exists page_uk1 on page (page_name);

create table if not exists page_tab (
  tab_id bigint generated by default as identity,
  tab_name varchar(255) not null,
  tab_index int not null,
  page_id bigint not null,
  constraint page_tab_fk1 foreign key (page_id) references page (page_id),
  primary key (tab_id)
);
create unique index if not exists page_tab_uk1 on page_tab (page_id, tab_name);

create table if not exists page_section (
  section_id bigint generated by default as identity,
  section_name varchar(255) not null,
  section_index int not null,
  section_split_ratio varchar(32) not null,
  tab_id bigint not null,
  constraint page_section_fk1 foreign key (section_split_ratio) references split_ratio (split_ratio_name),
  constraint page_section_fk2 foreign key (tab_id) references page_tab (tab_id),
  primary key (section_id)
);
create unique index if not exists page_section_uk1 on page_section (tab_id, section_name);

create table if not exists page_sub_section (
  sub_section_id bigint generated by default as identity,
  sub_section_name varchar(255) not null,
  sub_section_index int not null,
  section_id bigint not null,
  row_tag_type_id int,
  column_tag_type_id int,
  constraint page_sub_section_fk1 foreign key (section_id) references page_section (section_id),
  primary key (sub_section_id)
);
create unique index if not exists page_sub_section_uk1 on page_sub_section (section_id, sub_section_name);

create table if not exists series_data_key (
  key_id bigint generated by default as identity,
  key_name varchar(64) not null,
  key_title varchar(255),
  primary key (key_id)
);
create unique index if not exists series_data_key_uk1 on series_data_key (key_name);

create table if not exists series_data (
  series_data_id bigint generated by default as identity,
  series_data_date date not null,
  key_id bigint not null,
  series_data_value numeric(38,2) not null,
  currency_base char(3) not null,
  currency_code char(3) not null,
  series_data_title varchar(255),
  constraint series_data_fk1 foreign key (key_id) references series_data_key (key_id),
  constraint series_data_fk2 foreign key (currency_base) references currency (currency_code),
  constraint series_data_fk3 foreign key (currency_code) references currency (currency_code),
  primary key (series_data_id)
);
create index if not exists series_data_idx1 on series_data (key_id);
create unique index if not exists series_data_uk1 on series_data (series_data_date, key_id);

create table if not exists key_tag (
  key_id bigint,
  tag_id bigint,
  constraint key_tag_fk1 foreign key (key_id) references series_data_key (key_id),
  constraint key_tag_fk2 foreign key (tag_id) references tag (tag_id),
  primary key (key_id, tag_id)
);

create table if not exists sub_section_key (
  sub_section_id bigint,
  key_id bigint,
  constraint key_sub_section_fk1 foreign key (sub_section_id) references page_sub_section (sub_section_id),
  constraint key_sub_section_fk2 foreign key (key_id) references series_data_key (key_id),
  primary key (sub_section_id, key_id)
);

-- TODO: remove following lines later
-- alter table currency add column if not exists currency_base char(1);
-- alter table exchange add column if not exists exchange_base char(1);
-- alter table exchange modify exchange_mic varchar(5) not null;
-- alter table exchange_ticker modify exchange_mic varchar(5) not null;
-- alter table exchange_ticker modify ticker_symbol varchar(32) not null;
-- alter table exchange_ticker modify ticker_name varchar(255);
