-- DDL (schema) script

create table split_ratio (
  split_ratio_name varchar(32) not null,
  split_ratio_title varchar(255) not null,
  primary key (split_ratio_name)
);

create table tag_type (
  tag_type_id int generated by default as identity,
  tag_type_name varchar(32) not null,
  tag_type_title varchar(255),
  primary key (tag_type_id)
);

create table tag (
  tag_id bigint generated by default as identity,
  tag_name varchar(32) not null,
  tag_title varchar(255),
  tag_type_id int not null,
  primary key (tag_id),
  constraint tag_fk1 foreign key (tag_type_id) references tag_type (tag_type_id)
);
create index tag_idx1 on tag (tag_type_id, tag_name);

create table page (
  page_id bigint generated by default as identity,
  page_name varchar(255) not null,
  primary key (page_id)
);

create table page_tab (
  tab_id bigint generated by default as identity,
  tab_name varchar(255) not null,
  page_id bigint not null,
  primary key (tab_id),
  constraint page_tab_fk1 foreign key (page_id) references page (page_id)
);

create table page_section (
  section_id bigint generated by default as identity,
  section_name varchar(255) not null,
  section_index int not null,
  section_split_ratio varchar(32) not null,
  tab_id bigint not null,
  primary key (section_id),
  constraint page_section_fk1 foreign key (section_split_ratio) references split_ratio (split_ratio_name),
  constraint page_section_fk2 foreign key (tab_id) references page_tab (tab_id)
);

create table page_sub_section (
  sub_section_id bigint generated by default as identity,
  sub_section_name varchar(255) not null,
  section_id bigint not null,
  row_tag_type_id int,
  column_tag_type_id int,
  primary key (sub_section_id),
  constraint page_sub_section_fk1 foreign key (section_id) references page_section (section_id)
);

create table series_data_key (
  key_id bigint generated by default as identity,
  key_name varchar(64) not null,
  key_title varchar(255),
  primary key (key_id)
);

create table series_data (
  series_data_id bigint generated by default as identity,
  series_data_date date not null,
  series_data_value numeric(38,2) not null,
  series_data_title varchar(255),
  key_id bigint,
  constraint series_data_fk1 foreign key (key_id) references series_data_key (key_id),
  primary key (series_data_id)
);
create index series_data_idx1 on series_data (series_data_date, key_id);

create table key_tag (
  key_id bigint,
  tag_id bigint,
  primary key (key_id, tag_id),
  constraint key_tag_fk1 foreign key (key_id) references series_data_key (key_id),
  constraint key_tag_fk2 foreign key (tag_id) references tag (tag_id)
);

create table sub_section_key (
  sub_section_id bigint,
  key_id bigint,
  primary key (key_id, sub_section_id),
  constraint key_sub_section_fk1 foreign key (sub_section_id) references page_sub_section (sub_section_id),
  constraint key_sub_section_fk2 foreign key (key_id) references series_data_key (key_id)
);
