-- DDL (schema) script
create table series_data (
  series_id bigint generated by default as identity,
  series_date date,
  series_value numeric(38,2),
  series_title varchar(255) not null,
  primary key (series_id)
);
